apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: radicale-env
spec:
  path: kvv2/radicale
  type: Opaque
  templates:
    ADMIN_USER: "{% .Secrets.ADMIN_USER %}"
    ADMIN_PASSWORD: "{% .Secrets.ADMIN_PASSWORD %}"