apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: db-secret
spec:
  path: kvv2/homarr
  type: Opaque
  templates:
    db-url: "{% .Secrets.DB_URL %}"
    db-encryption-key: "{% .Secrets.DB_ENCRYPTION_KEY %}"
