apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: db-secret
spec:
  path: kvv2/homarr
  type: Opaque
  templates:
    db-url: "postgresql://{% .Secrets.DB_USER %}:{% .Secrets.DB_PASSWORD %}@pg-cluster-rw.postgres.svc.cluster.local:5432/homarr"
    db-encryption-key: "{% .Secrets.DB_ENCRYPTION_KEY %}"
