apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: auth-oidc-secret
spec:
  path: kvv2/homarr
  type: Opaque
  templates:
    oidc-client-id: "{% .Secrets.oidc-client-id %}"
    oidc-client-secret: "{% .Secrets.oidc-client-secret %}"
