apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: db-secret
spec:
  path: kvv2/homarr
  type: Opaque
  templates:
    db-url: "{% .Secrets.db-url %}"
    db-encryption-key: "{% .Secrets.db-encryption-key %}"
