persistence:
  homarrDatabase:
    enabled: false

database:
  type: postgresql

ingress:
  enabled: false

service:
  enabled: false

envSecrets:
  dbCredentials:
    dbUrlKey: db-url
    existingSecret: db-secret
  dbEncryption:
    key: db-encryption-key
    existingSecret: db-secret
