persistence:
  homarrDatabase:
    enabled: false

database:
  type: postgresql

ingress:
  enabled: false

service:
  enabled: true

envSecrets:
  dbCredentials:
    dbUrlKey: db-url
    existingSecret: db-secret
  dbEncryption:
    key: db-encryption-key
    existingSecret: db-secret

env:
  AUTH_OIDC_AUTO_LOGIN: true
  AUTH_OIDC_CLIENT_NAME: authentik
  AUTH_OIDC_GROUPS_ATTRIBUTE: groups
  AUTH_OIDC_ISSUER: https://auth.matiix310.dev/application/o/homarr/
  AUTH_OIDC_SCOPE_OVERWRITE: openid email profile groups
  AUTH_LOGOUT_REDIRECT_URL: https://auth.matiix310.dev/application/o/homarr/end-session/
  AUTH_PROVIDERS: oidc
