apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keeper-cron
  template:
    metadata:
      labels:
        app: keeper-cron
    spec:
      containers:
        - name: keeper-cron
          image: ghcr.io/ridafkih/keeper-cron:2.14.9
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pg-cluster-rw.postgres.svc.cluster.local:5432/keeper
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@keeper-redis.keeper.svc.cluster.local:6379
            - name: WORKER_JOB_QUEUE_ENABLED
              value: "true"
            - name: BLOCK_PRIVATE_RESOLUTION
              value: "true"
          envFrom:
            - secretRef:
                name: keeper-env
            - secretRef:
                name: keeper-pg
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"