apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keeper-cron
  template:
    metadata:
      labels:
        app: keeper-cron
    spec:
      containers:
        - name: keeper-cron
          image: ghcr.io/ridafkih/keeper-cron:2.14.9
          stdin: true
          tty: true
          env:
            - name: WORKER_JOB_QUEUE_ENABLED
              value: "true"
            - name: BLOCK_PRIVATE_RESOLUTION
              value: "true"
          envFrom:
            - secretRef:
                name: keeper-env
            - secretRef:
                name: keeper-pg
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"