apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
spec:
  secretName: tls-certificate
  issuerRef:
    name: prod-cluster-issuer
    kind: ClusterIssuer
  commonName: vaultwarden.matiix310.dev
  dnsNames:
    - "vaultwarden.matiix310.dev"
