apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: vaultwarden-env
spec:
  path: kvv2/vaultwarden
  type: Opaque
  templates:
    DOMAIN: "https://vaultwarden.matiix310.dev"
    SIGNUPS_ALLOWED: "false"
    ADMIN_TOKEN: "{% .Secrets.ADMIN_TOKEN %}"
