apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-issuer
spec:
  acme:
    email: lucas.stephan.12@outlook.fr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: lucas.stephan.12@outlook.fr
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: key