apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: trilium-oidc-secret
spec:
  path: kvv2/trilium
  type: Opaque
  templates:
    TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTID: "{% .Secrets.OIDC_CLIENT_ID %}"
    TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTSECRET: "{% .Secrets.OIDC_CLIENT_SECRET %}"
