apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: trilium-oidc-secret
spec:
  path: kvv2/trilium
  type: Opaque
  templates:
    TRILIUM_OAUTH_CLIENT_ID: "{% .Secrets.OIDC_CLIENT_ID %}"
    TRILIUM_OAUTH_CLIENT_SECRET: "{% .Secrets.OIDC_CLIENT_SECRET %}"
