controllers:
  main:
    containers:
      trilium:
        env:
          TRILIUM_OAUTH_BASE_URL: "https://wiki.matiix310.dev"
        envFrom:
          - secret: trilium-oidc-secret

configini:
  network:
    trustedReverseProxy: true
