apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memos-tls
spec:
  secretName: memos-tls
  issuerRef:
    name: prod-cluster-issuer
    kind: ClusterIssuer
  commonName: memos.matiix310.dev
  dnsNames:
    - "memos.matiix310.dev"
