apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: authentik-secret
spec:
  path: kvv2/authentik
  type: Opaque
  templates:
    AUTHENTIK_SECRET_KEY: "{% .Secrets.AUTHENTIK_SECRET_KEY %}"
