apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: authentik-postgres-credentials
spec:
  path: kvv2/authentik
  type: Opaque
  templates:
    username: "{% .Secrets.POSTGRES_USER %}"
    password: "{% .Secrets.POSTGRES_PASSWORD %}"
