apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: authentik-pg
spec:
  path: kvv2/authentik
  type: kubernetes.io/basic-auth
  templates:
    username: "{% .Secrets.POSTGRES_USER %}"
    password: "{% .Secrets.POSTGRES_PASSWORD %}"
