authentik:
  postgresql:
    host: postgres.authentik.svc.cluster.local
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
    name: authentik
    port: 5432
  existingSecret:
    secretName: authentik-secret
    secretKey: AUTHENTIK_SECRET_KEY

global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: "postgres.authentik.svc.cluster.local"
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-credentials
          key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-credentials
          key: password
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-credentials
          key: password
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-credentials
          key: username

postgresql:
  enabled: false

redis:
  enabled: true

server:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true

worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
