authentik:
  postgresql:
    host: postgres.authentik.svc.cluster.local
    user: file:///postgres-creds/POSTGRES_USER
    password: file:///postgres-creds/POSTGRES_PASSWORD

  existingSecret:
    secretName: authentik-postgres-credentials
    secretKey: AUTHENTIK_SECRET_KEY

server:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true

worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
