apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: affine-env
spec:
  path: kvv2/affine
  type: Opaque
  templates:
    DB_USERNAME: '{% .Secrets.DB_USERNAME | default "affine" %}'
    DB_PASSWORD: "{% .Secrets.DB_PASSWORD %}"
    DB_DATABASE: '{% .Secrets.DB_DATABASE | default "affine" %}'
    REDIS_SERVER_HOST: "redis"
    NODE_ENV: "production"
