apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: mysql-secret
spec:
  path: kvv2/openwork
  type: Opaque
  templates:
    ROOT_PASSWORD: "{% .Secrets.MYSQL_ROOT_PASSWORD %}"
    PASSWORD: "{% .Secrets.MYSQL_PASSWORD %}"
