apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - ingress.yaml
  - secret.yaml
  - secret-pg.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  - web/deployment.yaml
  - web/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - cron/deployment.yaml
  - worker/deployment.yaml
  - mcp/deployment.yaml
  - mcp/service.yaml