apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: block-signup
spec:
  redirectRegex:
    regex: ^/api/auth/(username-only/sign-up|sign-in/social|callback/google|callback/microsoft)/?$
    replacement: /auth-disabled
    permanent: false
