apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: keeper-env
spec:
  path: kvv2/keeper
  type: Opaque
  templates:
    BETTER_AUTH_SECRET: "{% .Secrets.BETTER_AUTH_SECRET %}"
    ENCRYPTION_KEY: "{% .Secrets.ENCRYPTION_KEY %}"
    REDIS_PASSWORD: "{% .Secrets.REDIS_PASSWORD %}"
    DATABASE_URL: "postgres://{% .Secrets.POSTGRES_USER %}:{% .Secrets.POSTGRES_PASSWORD %}@pg-cluster-rw.postgres.svc.cluster.local:5432/keeper"
    REDIS_URL: "redis://:{% .Secrets.REDIS_PASSWORD %}@keeper-redis.keeper.svc.cluster.local:6379"
    ENV: "production"
    NODE_ENV: "production"
    GOOGLE_CLIENT_ID: "{% .Secrets.GOOGLE_CLIENT_ID %}"
    GOOGLE_CLIENT_SECRET: "{% .Secrets.GOOGLE_CLIENT_SECRET %}"
    MICROSOFT_CLIENT_ID: "{% .Secrets.MICROSOFT_CLIENT_ID %}"
    MICROSOFT_CLIENT_SECRET: "{% .Secrets.MICROSOFT_CLIENT_SECRET %}"