apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blinko-route
spec:
  entryPoints:
    - websecure
  tls:
    secretName: blinko-tls
  routes:
    - match: Host(`blinko.matiix310.dev`)
      kind: Rule
      services:
        - name: blinko
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blinko-tls
spec:
  secretName: blinko-tls
  issuerRef:
    name: prod-cluster-issuer
    kind: ClusterIssuer
  commonName: blinko.matiix310.dev
  dnsNames:
    - "blinko.matiix310.dev"
