apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: blinko-env
spec:
  path: kvv2/blinko
  type: Opaque
  templates:
    NEXTAUTH_SECRET: "{% .Secrets.NEXTAUTH_SECRET %}"
    DATABASE_URL: "postgresql://{% .Secrets.POSTGRES_USER %}:{% .Secrets.POSTGRES_PASSWORD %}@pg-cluster-rw.postgres.svc.cluster.local:5432/blinko"
