apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: blinko-env
spec:
  path: kvv2/blinko
  type: Opaque
  templates:
    NEXTAUTH_SECRET: "{% .Secrets.NEXTAUTH_SECRET %}"
    DATABASE_URL: "{% .Secrets.DATABASE_URL %}"
