apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: prod-issuer
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cloudflare-api-token-secret
      key: key