apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: homarr-pg
spec:
  path: kvv2/homarr
  type: kubernetes.io/basic-auth
  templates:
    username: "homarr"
    password: "{% .Secrets.DB_PASSWORD %}"
