apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authentik-role.yaml
  - authentik-pg-secret.yaml
  - authentik-database.yaml
  - blinko-role.yaml
  - blinko-pg-secret.yaml
  - blinko-database.yaml
  - homarr-role.yaml
  - homarr-pg-secret.yaml
  - homarr-database.yaml
