apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: authentik
      repoURL: https://charts.goauthentik.io
      targetRevision: 15.11.0
      helm:
        valueFiles:
          - "$values/apps/authentik/values.yaml"
    - repoURL: https://github.com/avalon-infra/kube.git
      targetRevision: HEAD
      path: apps/authentik
      ref: values
  destination:
    name: in-cluster
    namespace: authentik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
