apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: quay.io/jetstack/charts
      targetRevision: v1.19.2
      helm:
        values: |
          installCRDs: true
    - repoURL: https://github.com/cloudflare/origin-ca-issuer
      targetRevision: v0.13.0
      path: deploy/crds
    - repoURL: https://github.com/cloudflare/origin-ca-issuer
      targetRevision: v0.13.0
      path: deploy/rbac
    - repoURL: https://github.com/cloudflare/origin-ca-issuer
      targetRevision: v0.13.0
      path: deploy/manifests
    - repoURL: https://github.com/avalon-infra/kube.git
      targetRevision: HEAD
      path: apps/cert-manager
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
