apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-crds-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kgateway-crds
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.2.0
    helm:
      skipCrds: false
      parameters:
        - name: controller.image.pullPolicy
          value: "Always"
        - name: controller.extraEnv.KGW_ENABLE_GATEWAY_API_EXPERIMENTAL_FEATURES
          value: "true"
  destination:
    name: in-cluster
    namespace: kgateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
