apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: v0.15.3
    - repoURL: https://github.com/avalon-infra/kube.git
      targetRevision: HEAD
      path: apps/metallb
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
