apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.32.0
      helm:
        values: |
          global:
            enabled: true
            tlsDisable: false
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 256Mi
                cpu: 250m
          
          injector:
            enabled: false

          server:
            # These Resource Limits are in line with node requirements in the
            # Vault Reference Architecture for a Small Cluster
            resources:
              requests:
                memory: 2Gi
                cpu: 500m
              limits:
                memory: 4Gi
                cpu: 500m

            # For HA configuration and because we need to manually init the vault,
            # we need to define custom readiness/liveness Probe settings
            # readinessProbe:
            #   enabled: true
            #   path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
            # livenessProbe:
            #   enabled: true
            #   path: "/v1/sys/health?standbyok=true"
            #   initialDelaySeconds: 60

            # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
            # used to include variables required for auto-unseal.

            # This configures the Vault Statefulset to create a PVC for audit logs.
            # See https://www.vaultproject.io/docs/audit/index.html to know more
            auditStorage:
              enabled: false

            volumes:
              - name: userconfig-vault-ha-tls
                secret:
                  defaultMode: 420
                  secretName: vault-tls

            volumeMounts:
              - mountPath: /vault/userconfig/vault-ha-tls
                name: userconfig-vault-ha-tls
                readOnly: true


            standalone:
              enabled: true
              replicas: 1
              raft:
                enabled: true
                setNodeId: true

                config: |
                  ui = true
                  cluster_name = "vault-integrated-storage"
                  listener "tcp" {
                    tls_disable = 0
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                    tls_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
                    tls_key_file  = "/vault/userconfig/vault-ha-tls/vault.key"
                    tls_client_ca_file = "/vault/userconfig/vault-ha-tls/vault.ca"
                  }

                  storage "raft" {
                    path = "/vault/data"
                  }
    - repoURL: https://github.com/avalon-infra/kube.git
      path: apps/vault
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
