apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: oci://ghcr.io/ricoberger/charts/vault-secrets-operator
    targetRevision: 3.1.5
    helm:
      values: |
        vault:
          address: "https://vault.matiix310.dev"
          authMethod: kubernetes
  destination:
    name: in-cluster
    namespace: vault-secrets-operator-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
