apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keeper-worker
  template:
    metadata:
      labels:
        app: keeper-worker
    spec:
      containers:
        - name: keeper-worker
          image: ghcr.io/ridafkih/keeper-worker:2.23.0
          env:
            - name: NODE_ENV
              value: PRODUCTION
          envFrom:
            - secretRef:
                name: keeper-env
            - secretRef:
                name: keeper-pg
