apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keeper-worker
  template:
    metadata:
      labels:
        app: keeper-worker
    spec:
      containers:
        - name: keeper-worker
          image: ghcr.io/ridafkih/keeper-worker:2.14.9
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pg-cluster-rw.postgres.svc.cluster.local:5432/keeper
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@keeper-redis.keeper.svc.cluster.local:6379
          envFrom:
            - secretRef:
                name: keeper-env
            - secretRef:
                name: keeper-pg
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"