apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tino-env
spec:
  path: kvv2/tino
  type: Opaque
  templates:
    OIDC_CLIENT_ID: "{% .Secrets.OIDC_CLIENT_ID %}"
    OIDC_CLIENT_SECRET: "{% .Secrets.OIDC_CLIENT_SECRET %}"
